### ISSUE TITLE
[GH Issue Summarization] Create build image

### ISSUE THREAD

**Issue by texasmichelle** [kubeflow/examples#10]
Build a docker image using Argo to be used by K8sJob, TFJob, TFServing, etc.

Component of #14.

**Comment by texasmichelle** [comment]
@vicaire do you have something already put together that we could use as a starting point for this?

**Comment by vicaire** [comment]
Happy to help. 

I have turned the steps from the notebook into a set of python commands. 

I have a Dockerfile that gathers all the dependencies. 

And I have a basic Argo workflow to run the steps one after the other. 

How would like this to be checked-in?

**Comment by texasmichelle** [comment]
@vicaire That's great! Fork the project in your own repo, create a branch, & submit a PR for merge back here to master. Unless @ankushagarwal has a different preference, since he is also working on this.

@ewilderj @jlewi Is there a contributor guide published somewhere with these guidelines?

**Comment by texasmichelle** [comment]
It probably makes sense to model the folder structure after [k8s/examples](https://github.com/kubernetes/examples).

**Comment by ankushagarwal** [comment]
Hi @vicaire I have been working on this as well. Can you check-in your code and I would be happy to review / improve it based on my experience of this example. #1 is a good example of structure.

**Comment by jlewi** [comment]
Lets have a top level directory for each example and then all code for that example should be in that directory.

If there's python code for the example I suggest putting that in

```
{example_dir}/py
```

The expectation should be this directory is added to the python path so that every subdirectory of py is a top level python package.

For Docker images. There's probably two sets of Docker images.

1. A docker image with all dependencies suitable for running the example (e.g. in Jupyter).
1. A docker image which is the first container plus the code for the example itself.

For #1 we could build a special Docker image just for this example but it might make sense just to add any python packages needed to our existing Jupyter notebook images.
https://github.com/kubeflow/kubeflow/tree/master/components/tensorflow-notebook-image

For #2 it would be nice to use Argo to start with that Docker image and then build a Docker image that is that base image + the source code (e.g. by checking out the code from GitHub).

This could be structured at a ksonnet app located at 

```
{example_dir}/workflows
```

**Comment by texasmichelle** [comment]
👍 to having a single notebook image

**Comment by ewilderj** [comment]
@texasmichelle kubeflow/CONTRIBUTING.md this the best we have right now. I think a good outcome from this thread would be a CONTRIBUTING file in examples/

**Comment by cwbeitel** [comment]
I like the idea of having a training image that is the demo/workspace image plus the trainer code. A point of friction in that approach is the increased size of the training image that will need to be built repeatedly 

```bash
gcr.io/kubeflow/tensorflow-notebook-cpu   latest                   169f860f283c        6 days ago          5.6GB
tensorflow/tensorflow                     1.5.0                    a2d1671e8a93        3 weeks ago         1.25GB
tensorflow/tensorflow                     1.4.1                    3cac069c491d        3 weeks ago         1.28GB
gcr.io/kubeflow/tensorflow-notebook-gpu   latest                   e68d36c67064        2 months ago        7.11GB
```

So in order to develop with reasonable velocity it would be good to have a way to cache from prior builds. But I think that is very solvable and otherwise I agree that this approach makes the most sense.

Perhaps the correct means of doing so is subject for a separate issue but my understanding so far is that the two options are 
1. using `docker save...` and `docker load...` to and from NFS or 
2. using an in-cluster container registry

See also [this](https://github.com/cwbeitel/examples/blob/50c9dd425493212b8d103f11001e4874274561ec/agents/tools/builder/builder.yaml) and [this](https://github.com/cwbeitel/examples/blob/50c9dd425493212b8d103f11001e4874274561ec/agents/doc/demo.ipynb) and [this](https://github.com/kubeflow/example-seldon/blob/master/workflows/training-tf-mnist-workflow.yaml).

**Comment by jlewi** [comment]
@vicaire any chance you can submit a PR with what you have?

**Comment by vicaire** [comment]
Yes, sorry for the delay. Let me work on this between today and tomorrow.

**Comment by vicaire** [comment]
Here is a PR with a basic container image and Argo workflow: 

https://github.com/kubeflow/examples/pull/35

Let me know your comments.
