### ISSUE TITLE
[mnist_pytorch] Implement E2E tests

### ISSUE THREAD

**Issue by dsdinter** [kubeflow/examples#312]
We should have E2E tests that cover:

1. Training the model
1. Deploying the model
1. Client code to send predictions
1. Notebook (if there is one)

**Comment by jlewi** [comment]
I'm working on adding tests to the GitHub issue summarization example. We can use that as a model for adding tests to this example.

In addition here are some other resources:

1. [General instructions](https://github.com/kubeflow/testing#writing-an-argo-workflow-for-an-e2e-test) for writing an Argo workflow to be used as an E2E test 

1. [Guide To Writing Tests for E2E examples](http://bit.ly/kf_example_testing_guide) - This is in an in progress doc to come up with instructions for writing E2E tests.

I'm bumping this to priority P1 because we currently use mnist as part of our getting started guides; e.g https://www.kubeflow.org/docs/guides/gke/gcp-e2e/

**Comment by dsdinter** [comment]
Thanks for that @jlewi, happy to contribute to your guide as well, actually I started to look at Unittests during Christmas and saw you have a [section](https://docs.google.com/document/d/1iaVTjr9XVQYb1_kdpq__vq9S9hHaDrX31LWqRs3aujc/edit#heading=h.4ch59sds05bu) included in your guide.
The good news is that I already implemented the Argo workflow E2E tests in the Pytorch example to automate building and pushing the images to the official repo.

**Comment by jlewi** [comment]
@dsdinter Any update on this? Think we'll be able to get #490 submitted by the end of the month?

**Comment by dsdinter** [comment]
It's doable, just need to finish a few things this week to have capacity for next.
