### ISSUE TITLE
Lint broken for examples test and not running on post-submit and periodic

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#505]
The lint test doesn't appear to be running on periodic post-submits
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-examples

It also looks like it is broken at head.

@zhenghuiwang

**Comment by zhenghuiwang** [comment]
All lint errors are caused by `py` (tf-operator/py) module not found: The ci-worker doesn't checkout `kubeflow/tf-operator` source code in this case. 

One way to fix is to change the worker to always check out tf-operator and add it to PATHONPATH env (similar to `testing/py`). This seems to be an overkill for fixing the lint.

Instead, I add `#pylint: disable" to ignore the import checks. Let me know if you think there is a better way.

**Comment by jlewi** [comment]
@zhenghuiwang I think that's fine. Were the lint issues fixed in #493?

**Comment by zhenghuiwang** [comment]
Yes, #493 fixed it. I'm going to close this issue.
