### ISSUE TITLE
The cluster `kf-vmaster-n00` for kubeflow-examples-presubmit no longer exists

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/examples#549]
Seems the cluster `kf-vmaster-n00` for kubeflow-examples-presubmit is removed?

`get-kubeconfig` component log are as following:

```
W
+ gcloud auth activate-service-account --key-file=/secret/gcp-credentials/key.json
Activated service account credentials for: [kubeflow-testing@kubeflow-ci.iam.gserviceaccount.com]
+ gcloud --project=kubeflow-ci-deployment container clusters get-credentials --zone=us-east1-b kf-vmaster-n00
Fetching cluster endpoint and auth data.
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=404, message=Not found: projects/kubeflow-ci-deployment/zones/us-e
ast1-b/clusters/kf-vmaster-n00.
No cluster named 'kf-vmaster-n00' in kubeflow-ci-deployment.
```

/cc @jlewi 
Anyone can help to check the env? Thanks a lot!

**Comment by jinchihe** [comment]
@jlewi is the cluster changed? how to get the new cluster name? Thanks a lot!

**Comment by jlewi** [comment]
It looks like kf-v05-n00 didn't get deployed because we ran out of quota. Other clusters should be available

What we should be doing now in the test is using this script
https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/get_kf_testing_cluster.py as one step in the pipeline to automatically determine what cluster to use and get credentials for that cluster.

Any interest in sending a different PR (lets not block #546) to update the test to use that script to determine which cluster to use?

As a quick fix though I think you can just change the cluster to
 kf-v0-5-n04

**Comment by jinchihe** [comment]
@jlewi Great thanks for the replying. but seems the `kf-v0-5-n04` also does not work properly while checkout code due to no space left.

```
+ SRC_DIR=/mnt/test-data-volume/kubeflow-examples-presubmit-mnist-546-2c79014-9648-d382/src
+ mkdir -p /src/kubeflow
+ git clone https://github.com/kubeflow/examples.git /mnt/test-data-volume/kubeflow-examples-presubmit-mnist-546-2c79014-9648-d382/src/ku
beflow/examples
fatal: could not create leading directories of '/mnt/test-data-volume/kubeflow-examples-presubmit-mnist-546-2c79014-9648-d382/src/kubeflo
w/examples': No space left on device
```

**Comment by jinchihe** [comment]
@jlewi I'm going to create a PR to update the test to use that `get_kf_testing_cluster.py` to determine which cluster to use. Thanks.

**Comment by jlewi** [comment]
@jinchihe Has this been fixed? Is the test still broken?

**Comment by jinchihe** [comment]
@jlewi  The problem cannot be reproduced recently, I think that should be fixed. Thanks.
