### ISSUE TITLE
[codelab-minikf-kale-feedback]: Problem at step Click Launch to create the notebook server.

### ISSUE THREAD

**Issue by navneetkrc-aj** [kubeflow/examples#712]
Problem after step Click Launch to create the notebook server.
Not able to reach the step -
When the notebook server is available, click Connect to connect to it.

Status bar keeps on rotating and I am not able to connect to Notebook Server.
<img width="1156" alt="Not able to launch the Notebook Servers" src="https://user-images.githubusercontent.com/49390926/72729685-c0eb8000-3bb5-11ea-9778-d4b25060d6a5.png">

**Comment by Prajesh7** [comment]
Can someone please suggest a solution!? I am also facing the same issue. @navneetkrc-aj If you did find a solution, can you please share it. Thank you.

**Comment by jbottum** [comment]
@Prajesh7 @navneetkrc- - Sorry that the community did not respond.    As you may know Kale was developed by Arrikto and most of the Arrikto employees are working at Canonical or HPE.  I will put this on the agenda for the next community meeting and see if we can get some movement.    Again, I apologize that we did not get back

**Comment by Prajesh7** [comment]
Thank you so much @jbottum. All the stable and easily deployable versions of Kubeflow are blocked behind a pay wall. This seriously cuts down its adaptation and usability. I request you to please make at least one version one click deplyable so that a data scientist is not road blocked by the massive complexity of it. Thank you very much for the help.
