### ISSUE TITLE
create replacement gke pipelines example

### ISSUE THREAD

**Issue by amygdala** [kubeflow/examples#727]
assigning to moi.  I am working on a new codelab that should be a good fit.

See https://github.com/kubeflow/examples/pull/726 , kubeflow/pipelines#3037, kubeflow/website#1611

**Comment by jlewi** [comment]
@amygdala Could we create a KF compatible notebook to run the example E2E so its easy to test and so users don't have to actually type anything?

If at all possible, could we have the pipeline use GitOps; so rather than have the pipeline directly deploy the model the final step in the model would be to push a commit updating the K8s deployment yaml to use the latest model,

We can then use something like ArgoCD or [Anthos CM](https://cloud.google.com/anthos-config-management/docs/) to keep the K8s resources in sync.

I think GitOps is more in line where the industry is headed then directly updating the model.

If we use Google Cloud Source Repos then we should be able to programmatically (in the notebook) setup the repo and then in the pipeline authenticate to it using GCP credentials.

We could also eventually support GitHub but credentials are a bit more complicated (e.g. you need to mount SSH keys).
